### ISSUE TITLE
Suggestions for commands and placeholders!!

### ISSUE THREAD

**Issue by Pointzs** [ImNotStable/QualityEconomy#2]
Can you make it so that we can do /eco <player> <set/remove/add> 1k,1m,1b,1t. e.g. if i wanted to set someones balance to 100,000 i can type /eco someone set 100k.

Also could you do the same with /pay so that i can do /pay <player> 100k instead of /pay <player> 100000. 

Also please add a placeholder to show the baltop balance rather than just the players name of baltop place 1

**Comment by Pointzs** [comment]
also just in addition to what i have said above. are you able to swap around the /eco parameters so that its /eco <reset/set/add/remove> <player> <amount> instead of /eco <player> <reset/set/add/remove> <amount>

**Comment by Pointzs** [comment]
Also when someone hit 1B balance then it shows 1e10 instead of 1B on their baltop, server total balance and on the %qualityeconomy_balance% placeholder

**Comment by ImNotStable** [comment]
Is this right

- [ ] Add ability to use shortened versions of numbers in commands (Ex: 1k, 1M, 1B, 1T)
- [ ] Fix numbers in placeholders being shortened
- [ ] Added a placeholder for getting balance of balancetop

I'm not sure what you meant with the `/eco <reset/set/add/remove>` comment though.

**Comment by Pointzs** [comment]
What i mean by the /eco <reset/set/add/remove> comment is can you make it so i can do /eco <reset/set/add/remove> instead of /eco <player> <reset/set/add/remove>? its not exactly any issue and is more of a preference thing due to other plugins i have used in the past

**Comment by Pointzs** [comment]
> * [ ]  Add ability to use shortened versions of numbers in commands (Ex: 1k, 1M, 1B, 1T)
> * [ ]  Added a placeholder for getting balance of balancetop


Yes these 2 are corred but the middle one isnt exactly what i mean. what i mean is make it so it shows the suffix of K M B T Q QT when they hit that balance because currently it converts to the standard number form when they hit above the integer limit of minecraft. so it shows 1e10 instead of 1B or 1,000,000,000

**Comment by ImNotStable** [comment]
> What i mean by the /eco <reset/set/add/remove> comment is can you make it so i can do /eco <reset/set/add/remove> instead of /eco <reset/set/add/remove>? its not exactly any issue and is more of a preference thing due to other plugins i have used in the past

I made this so the code was easier to read, sorry but I will not be changing this within the plugin. However I will be doing what I listed above.

**Comment by Pointzs** [comment]
> > What i mean by the /eco <reset/set/add/remove> comment is can you make it so i can do /eco <reset/set/add/remove> instead of /eco <reset/set/add/remove>? its not exactly any issue and is more of a preference thing due to other plugins i have used in the past
> 
> I made this so the code was easier to read, sorry but I will not be changing this within the plugin. However I will be doing what I listed above.

Alright that is fine. either way i will be sticking to this plugin as it is light weight and very simple to use. other than the issues with the CommandAPI or whatever it was

**Comment by ImNotStable** [comment]
1.4.5 has been released.
