### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Pointzs** [ImNotStable/QualityEconomy#3]
when i do /eco <player> add 1000 in game i see "An unexpected error occured trying to execute that command" while the command still runs and i do still receive the money but in console it floods with this. for a server that is going to have this command run many times everyday due to crates being opened and rewards involving money this can make it hard to then go back to check logs when things such as roll backs happen where users loose huge amounts of their money. Please could this issue be fixed asap.

**[21:28:57 INFO]: LmaoLoq issued server command: /eco LmaoLoq add 1000**
d.java:70) ~[QualityEconomy-1.4.4.jar:?]at **com.imnotstable.qualityeconomy.commandapi.executors.CommandExecutor.run(CommandExecutor.java:49) ~[QualityEconomy-1.4.4.jar:?]at com.imnotstable.qualityeconomy.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:44) ~[QualityEconomy-1.4.4.jar:?]at com.imnotstable.qualityeconomy.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:137) ~[QualityEconomy-1.4.4.jar:?]at com.imnotstable.qualityeconomy.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:124) ~[QualityEconomy-1.4.4.jar:?]at com.imnotstable.qualityeconomy.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:91) ~[QualityEconomy-1.4.4.jar:?]at** com.imnotstable.qualityeconomy.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:258) ~[QualityEconomy-1.4.4.jar:?]at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.18.2.jar:?]at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:178) ~[paper-1.18.2.jar:?]at net.minecraft.commands.Commands.performCommand(Commands.java:293) ~[?:?]at org.bukkit.craftbukkit.v1_18_R2.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[paper-1.18.2.jar:git-Paper-388]at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-388]at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-388]at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-388]at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-388]at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-388]at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-388]at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ImNotStable** [comment]
There seems to be an issue with the API I used for my commands, I'll post an issue there. Until then I'm unsure of what I can do as this isn't something I can directly fix. What plugin are you using and are you aware if you can hook into vault and add the money that way?

**Comment by Pointzs** [comment]
> What plugin are you using and are you aware if you can hook into vault and add the money that way?

What do you mean what plugin am i using? I am using your economy plugin for the economy along with Vault 1.7.1 and PlaceholderAPI 2.11.5

**Comment by ImNotStable** [comment]
I meant for the crates

**Comment by Pointzs** [comment]
> I meant for the crates

Ahh im using the AdvancedCrates plugin. this plugin from what i know of doesnt hook into vault and essentially makes you type in a command for it to run when a player gets a reward. so essentially if a player gets money as their reward it will run the /eco add command to give them their money

**Comment by ImNotStable** [comment]
Alright, I've created an issue on the CommandAPI Github. I'll see what can be done.

**Comment by ImNotStable** [comment]
Could you get this log back and post the full stack trace (error)

**Comment by ImNotStable** [comment]
To be honest I'm unsure how the bug was fixed. Please create a new issue if it reappears.
