### ISSUE TITLE
WithDraw & baltop commands + placeholders.

### ISSUE THREAD

**Issue by Pointzs** [ImNotStable/QualityEconomy#5]
the withdraw command works perfectly but the item is the problem. I don't want it to be italic for the name and lore but it is even though my messages.config has it set to only be coloured and bold.

The placeholders work perfectly other than the one simple fact that on the %qualityeconomy_balance% placeholder it doesnt show the formatted balance with commas or M B K T QT Q when players have hit those balances. when i hit 1M it shows 1000000 not 1,000,000 or   1M.

On /baltop it still show server total as the unformatted balance. e.g. if server total is 1M it still shows 1e6 rather than 1,000,000.

**Comment by Pointzs** [comment]
[15:34:38 INFO]: LmaoLoq issued server command: /qe reload
[15:34:38 INFO]: [com.zaxxer.hikari.HikariDataSource] QualityEconomyPool - Shutdown initiated...
[15:34:38 INFO]: [com.zaxxer.hikari.HikariDataSource] QualityEconomyPool - Shutdown completed.
[15:34:38 ERROR]: Caught previously unhandled exception :
[15:34:38 ERROR]: Paper Async Task Handler Thread - 15
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:374) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:34:38 ERROR]: Caught previously unhandled exception :
[15:34:38 ERROR]: Paper Async Task Handler Thread - 16
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:374) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:34:38 ERROR]: Caught previously unhandled exception :
[15:34:38 ERROR]: Paper Async Task Handler Thread - 17
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:380) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:34:38 ERROR]: Caught previously unhandled exception :
[15:34:38 ERROR]: Paper Async Task Handler Thread - 18
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:374) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:34:38 ERROR]: Caught previously unhandled exception :
[15:34:38 ERROR]: Paper Async Task Handler Thread - 19
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:380) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:34:38 INFO]: [com.zaxxer.hikari.HikariDataSource] QualityEconomyPool - Starting...
[15:34:38 INFO]: [com.zaxxer.hikari.pool.HikariPool] QualityEconomyPool - Added connection conn30: url=jdbc:h2:./plugins/QualityEconomy/playerdata user=
[15:34:38 INFO]: [com.zaxxer.hikari.HikariDataSource] QualityEconomyPool - Start completed.
[15:34:38 INFO]: [QualityEconomy] Successfully initiated storage processes
[15:34:38 ERROR]: Caught previously unhandled exception :
[15:34:38 ERROR]: Paper Async Task Handler Thread - 20
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:380) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:34:38 ERROR]: Caught previously unhandled exception :
[15:34:38 ERROR]: Paper Async Task Handler Thread - 21
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:374) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:34:38 ERROR]: Caught previously unhandled exception :
[15:34:38 ERROR]: Paper Async Task Handler Thread - 22
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:374) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:34:38 ERROR]: Caught previously unhandled exception :
[15:34:38 ERROR]: Paper Async Task Handler Thread - 23
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:374) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:34:38 ERROR]: Caught previously unhandled exception :
[15:34:38 ERROR]: Paper Async Task Handler Thread - 24
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:374) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:34:38 ERROR]: Caught previously unhandled exception :
[15:34:38 ERROR]: Paper Async Task Handler Thread - 25
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:380) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
eractEvent(CraftEventFactory.java:498) ~[paper-1.18.2.jar:git-Paper-388]at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1910) ~[?:?]at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:28) ~[?:?]at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-388]at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-388]at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-388]at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-388] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-388]at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-388]at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-388]at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Pointzs** [comment]
edited config.yml and messages.yml and this happened when i reloaded

**Comment by Pointzs** [comment]
# This is the storage type the plugin will use
# Choose one of the options below
# h2, sqlite, mysql, mariadb
storage-type: h2

# Amount of decimal places allowed within balances
# -1 to disable rounding
decimal-places: 3

# Whether you want players to be able to withdraw
# they're money to 'checks' or 'banknotes'
banknotes: true

# Whether you want these commands enabled
commands:
  balance: true
  balancetop: true
  economy: true
  pay: true
  request: true
  custombalance: false
  customeconomy: false

# Whether you want custom currency functionality enabled.
custom-currencies: false

# Number in hours (decimals allowed)
# 0 to disable
backup-interval: 12

# Number in seconds
# 0 to disable
balancetop-interval: 300
autosave-accounts-interval: 10

database-information:
  database: database-name
  address: localhost
  port: 0
  username: username
  password: password

  advanced-settings:
    maximum-pool-size: 10
    minimum-idle: 10
    maximum-lifetime: 1800000
    keepalive-time: 0
    connection-timeout: 5000

**Comment by Pointzs** [comment]
Withdraw command has also disabled it self after reloading

**Comment by Pointzs** [comment]
i am using paper spigot 1.18.2
i am using qualityeconomy 1.4.5
i am using placeholderAPI 2.11.5
i am using Vault 1.7.3

**Comment by ImNotStable** [comment]
I will look into this once I get home. This will be in about 3 1/2 hours.

**Comment by Pointzs** [comment]
> I will look into this once I get home. This will be in about 3 1/2 hours.

All good. i'm not sure why this keeps breaking the withdraw command only though

**Comment by Pointzs** [comment]
Also when using the %qualityeconomy_balancetop_balance_#% %qualityeconomy_balancetop_#% placeholders I found an issue. if you add the placeholders for the numbers 1 - 10 but only 1 player has joined the server it will break the plugin i'm using for making the leaderboard for baltop. I am using deluxemenus to make the leaderboard. i have not tried using anything else to see if the same thing happens.

**Comment by Pointzs** [comment]
If i set the integer value to 1 and remove 2 - 10 then it works perfectly fine

**Comment by ImNotStable** [comment]
Sorry, but I'm not sure what you mean.

**Comment by Pointzs** [comment]
> Sorry, but I'm not sure what you mean.

When i do %qualityeconomy_balancetop_#1% the placeholder on the leaderboard works fine because one player has joined the server. But when i do the same thing but for second place it doesnt work and throws a bunch of errors

**Comment by Pointzs** [comment]
[00:45:18 INFO]: SupremeConCon issued server command: /lb
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
at com.extendedclip.deluxemenus.menu.MenuItem.getItemStack(MenuItem.java:298) ~[DeluxeMenus-1.14.0-Release.jar:?]at com.extendedclip.deluxemenus.menu.Menu.lambda$openMenu$5(Menu.java:418) ~[DeluxeMenus-1.14.0-Release.jar:?]at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-388]at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-388]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ImNotStable** [comment]
Oh I assume a second player never joined?

**Comment by Pointzs** [comment]
since adding the Plugin no a second player hadnt joined but once a second
had joined it works fine. but i have seen other plugins that dont require
every player to have joined because they return NO DATA if there is no data
for that spot

**Comment by ImNotStable** [comment]
I'll add format options for balances, this will take some time as I'm currently working on other aspects of the plugin. I have a commit that has fixed the server total within balancetop and the placeholder balancetop issue.
