### ISSUE TITLE
Console error. reload command.

### ISSUE THREAD

**Issue by Pointzs** [ImNotStable/QualityEconomy#6]
[15:29:03 INFO]: LmaoLoq issued server command: /qe reload
[15:29:03 INFO]: [com.zaxxer.hikari.HikariDataSource] QualityEconomyPool - Shutdown initiated...
[15:29:03 INFO]: [com.zaxxer.hikari.HikariDataSource] QualityEconomyPool - Shutdown completed.
[15:29:03 ERROR]: Caught previously unhandled exception :
[15:29:03 ERROR]: Paper Async Task Handler Thread - 0
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:380) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:29:03 ERROR]: Caught previously unhandled exception :
[15:29:03 ERROR]: Paper Async Task Handler Thread - 1
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:374) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:29:03 ERROR]: Caught previously unhandled exception :
[15:29:03 ERROR]: Paper Async Task Handler Thread - 2
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:374) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:29:03 INFO]: [com.zaxxer.hikari.HikariDataSource] QualityEconomyPool - Starting...
[15:29:03 INFO]: [com.zaxxer.hikari.pool.HikariPool] QualityEconomyPool - Added connection conn10: url=jdbc:h2:./plugins/QualityEconomy/playerdata user=
[15:29:03 INFO]: [com.zaxxer.hikari.HikariDataSource] QualityEconomyPool - Start completed.
[15:29:03 INFO]: [QualityEconomy] Successfully initiated storage processes
[15:29:03 ERROR]: Caught previously unhandled exception :
[15:29:03 ERROR]: Paper Async Task Handler Thread - 3
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:380) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:29:03 ERROR]: Caught previously unhandled exception :
[15:29:03 ERROR]: Paper Async Task Handler Thread - 4
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:374) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:29:03 ERROR]: Caught previously unhandled exception :
[15:29:03 ERROR]: Paper Async Task Handler Thread - 5
java.util.ConcurrentModificationException: nullat java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:414) ~[?:?]at net.minecraft.commands.Commands.sendAsync(Commands.java:374) ~[?:?]at net.minecraft.commands.Commands.sendCommands(Commands.java:364) ~[?:?]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ImNotStable** [comment]
You can ignore these errors as long as there are no issues with commands registering. If all commands work please close this issue. This is an issue within CommandAPI and they are already working on a fix.

**Comment by Pointzs** [comment]
alright

**Comment by Pointzs** [comment]
Not all commands are working
i have made a separate issue for that though
